version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: wp_db
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - red_wordpress

  wordpress:
    image: wordpress:latest
    container_name: wp_app
    restart: always
    depends_on:
      - db
    env_file: .env
    ports:
      - "${WP_PORT}:80"
    volumes:
      - wp_files:/var/www/html
    networks:
      - red_wordpress

volumes:
  db_data:
  wp_files:

networks:
  red_wordpress:
    external: false
    name: red_wordpress